FROM node:20-slim

WORKDIR /app

# Install openssl and other dependencies
RUN apt-get update -y && apt-get install -y openssl netcat-openbsd

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

# Ensure entrypoint is executable
RUN chmod +x ./docker-entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["./docker-entrypoint.sh"]
